// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	config "github.com/cwdsuzhou/super-scheduling/pkg/apis/config"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*SchedulingArgs)(nil), (*config.SchedulingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1beta1_SchedulingArgs_To_config_SchedulingArgs(a.(*SchedulingArgs), b.(*config.SchedulingArgs), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*config.SchedulingArgs)(nil), (*SchedulingArgs)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_config_SchedulingArgs_To_v1beta1_SchedulingArgs(a.(*config.SchedulingArgs), b.(*SchedulingArgs), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_SchedulingArgs_To_config_SchedulingArgs(in *SchedulingArgs, out *config.SchedulingArgs, s conversion.Scope) error {
	if err := v1.Convert_Pointer_string_To_string(&in.KubeConfigPath, &out.KubeConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_SchedulingArgs_To_config_SchedulingArgs is an autogenerated conversion function.
func Convert_v1beta1_SchedulingArgs_To_config_SchedulingArgs(in *SchedulingArgs, out *config.SchedulingArgs, s conversion.Scope) error {
	return autoConvert_v1beta1_SchedulingArgs_To_config_SchedulingArgs(in, out, s)
}

func autoConvert_config_SchedulingArgs_To_v1beta1_SchedulingArgs(in *config.SchedulingArgs, out *SchedulingArgs, s conversion.Scope) error {
	if err := v1.Convert_string_To_Pointer_string(&in.KubeConfigPath, &out.KubeConfigPath, s); err != nil {
		return err
	}
	return nil
}

// Convert_config_SchedulingArgs_To_v1beta1_SchedulingArgs is an autogenerated conversion function.
func Convert_config_SchedulingArgs_To_v1beta1_SchedulingArgs(in *config.SchedulingArgs, out *SchedulingArgs, s conversion.Scope) error {
	return autoConvert_config_SchedulingArgs_To_v1beta1_SchedulingArgs(in, out, s)
}
